pipelines:
  "gocd-yaml-plugin":
    group: gocd
    label_template: "${git[:8]}"
    locking: off
    materials:
      git:
        git: git@github.com:tomzo/gocd-yaml-config-plugin.git
    stages:
      - build:
          clean_workspace: true
          elastic_profile_id: w.c2.m2048.e10
          artifacts:
           - build:
               source: build/libs/*.jar
               destination: build/libs
          tasks:
           - exec:
               command: ide
               arguments:
                - gradle test jar
      - release:
          approval: manual
          clean_workspace: true
          elastic_profile_id: w.c2.m2048.e10
          secure_variables:
            GITHUB_TOKEN: pAecqdOB4Fqa/YMwIQsoZf59vDSZKMSTPkwmZuX5DjcXw/4xA5ZlFBza1ujZS8Ff
          tasks:
            - fetch:
                stage: build
                job: build
                source: build/libs
                destination: build
            - exec:
                command: /bin/bash
                arguments:
                  - ./release.sh
