pipelines:
  "gocd-yaml-plugin":
    group: gocd
    label_template: "${git[:8]}"
    locking: off
    materials:
      git:
        git: git@github.com:tomzo/gocd-yaml-config-plugin.git
    stages:
      - build:
          clean_workspace: true
          elastic_profile_id: w.c2.m2048.e10
          artifacts:
           - build:
               source: build/libs/*.jar
               destination: build/libs
          tasks:
           - exec:
               command: ide
               arguments:
                - gradle test jar
      - docker:
          clean_workspace: true
          resources:
            - docker_builder
          artifacts:
            - build:
                source: "docker/imagerc*"
                destination:
          tasks:
            - fetch:
                stage: build
                job: build
                source: build/libs
                destination: docker
            - exec:
                command: /bin/bash
                arguments:
                  - ./tasks.sh
                  - build_docker
            - exec:
                command: /bin/bash
                arguments:
                  - -c
                  - "ops_docker_push=true ./tasks.sh build_docker"
      - release:
          approval: manual
          clean_workspace: true
          jobs:
            github:
              elastic_profile_id: w.c2.m2048.e10
              secure_variables:
                GITHUB_TOKEN: "AES:+QBztHVft9PmbwLLgpXvhA==:QHWQ+Ya2aJF2HoYo2G6LGlb2thWekhXiO626YKcEfeCw0IH7ornkOf7F91+RetOY"
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: build/libs
                    destination: build
                - exec:
                    command: /bin/bash
                    arguments:
                      - ./tasks.sh
                      - github_release
            dockerhub:
              resources:
                - docker_builder
              secure_variables:
                DOCKERHUB_PASSWORD: "AES:Q/TQoBrYjWDf43TbbUzSUQ==:2w9UDmYJPgEU2bmuzuehjw=="
              tasks:
                - fetch:
                   stage: docker
                   job: docker
                   source: imagerc
                   destination: docker/
                   is_file: true
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks.sh publish_docker_public
      - bump:
          clean_workspace: true
          jobs:
            patch:
              elastic_profile_id: w.c2.m2048.e10
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - ./tasks.sh
                      - set_version
                - exec:
                    command: git
                    arguments:
                      - push
                      - origin
                      - master
